### ISSUE TITLE
Custom Commands is causing an error booting up

### ISSUE THREAD

**Issue by shadowolfyt** [TerraMagnum/TerraTools#12]
https://pastebin.com/3bLhtw3Z

**Comment by jasoryeh** [comment]
Ye it should be fixed in next commit. Still fixing errors on my end mate.

**Comment by shadowolfyt** [comment]
I fixed it you forgot to put false on some child permissions (on kick stop and reload)
![image](https://cloud.githubusercontent.com/assets/15405528/25114020/d3076204-243e-11e7-986b-fdc6d4a013b5.png)

**Comment by jasoryeh** [comment]
Durr

**Comment by jasoryeh** [comment]
Ye I already knew that
