### ISSUE TITLE
Fix missing required library Project should be compatible with spigot 1.11.2

### ISSUE THREAD

**Issue by shadowolfyt** [TerraMagnum/TerraTools#7]
Project 'CustomCommands' is missing required library: 'C:\Users\JasorYEH\Desktop\My Projects\First Minecraft Server Plugin\New 1.8 Bukkit and or Spigot\craftbukkit-1.8.8.jar'	CustomCommands		Build path	Build Path Problem

**Comment by jasoryeh** [comment]
Just re-import the jar file.
